### ISSUE TITLE
Is it ready to use?

### ISSUE THREAD

**Issue by OnlyBelter** [sebotic/cdk_pywrapper#1]
Is it ready to use? Is there any document for how to use it?

**Comment by DimitrisAlivas** [comment]
Following...

**Comment by sebotic** [comment]
yes, it's fully functional. I actually added a few updated which make installation more convenient and added fingerprinting and Tanimoto coefficient calculation.

**Comment by sebotic** [comment]
I added a basic example, the rest should be self-explanatory
