### ISSUE TITLE
How to specify type of fingerprint to calculate?

### ISSUE THREAD

**Issue by Limsande** [sebotic/cdk_pywrapper#5]
Hi,

I see there is a `get_fingerprint()` method, but I can't figure out how to specify the type of fingerprint to calculate, e.g. MACCS  or Substructure. Is this possible?

Yours,
Luis

**Comment by oivulf** [comment]
Please consider the following diff adding support for 7 common use fingerprints.
[fingerprints.diff.txt](https://github.com/sebotic/cdk_pywrapper/files/3926058/fingerprints.diff.txt)

**Comment by Limsande** [comment]
Awesome, that's exactly what I was looking for. Sorry for the late response, this was somehow buried in my inbox.
